spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/ProjectManagement
    username: root
    password: Ldb@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      read-only: false  # Ensure read-only is set to false
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

  cache:
    type: redis
    redis:
      time-to-live: 60000
  data:
    redis:
      host: localhost
      port: 6379
#    cors:
#      allowed-headers: "Authorization,Link,X-Total-Count"
#      allowed-methods: ${"*"}
#      allow-credentials: true
#      max-age: 1800
#      allowed-origin-patterns: ${"*"}


