spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/ProjectManagement
    username: root
    password: Ldb@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml
#  graphql:
#    cors:
#      allowed-headers: "Authorization,Link,X-Total-Count"
#      allowed-methods: ${"*"}
#      allow-credentials: true
#      max-age: 1800
#      allowed-origin-patterns: ${"*"}


